In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('forest fire.csv')

In [3]:
data.head()

Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1

In [4]:
data.describe()

Oxygen  Temperature    Humidity  Fire Occurrence
count  39.000000    39.000000   39.000000        39.000000
mean   33.846154    33.794872   36.282051         0.512821
std    23.734872    16.225677   28.046905         0.506370
min     0.000000     0.000000    0.000000         0.000000
25%    11.500000    20.000000   13.500000         0.000000
50%    30.000000    35.000000   30.000000         1.000000
75%    50.000000    45.000000   62.500000         1.000000
max    89.000000    60.000000  100.000000         1.000000

In [5]:
data.head(10)

Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1
5          c      50           15        30                0
6         de       5           35        35                0
7        asd       5           20        70                0
8    Ecuador      60           32        19                1
9          r      30           50        45                1

In [6]:
data = np.array(data)

In [7]:
print(data)

[['Jharkand' 40 45 20 1]
 ['Bangalore' 50 30 10 1]
 ['Ecuador' 10 20 70 0]
 ['a' 60 45 70 1]
 ['Bangalore' 30 48 10 1]
 ['c' 50 15 30 0]
 ['de' 5 35 35 0]
 ['asd' 5 20 70 0]
 ['Ecuador' 60 32 19 1]
 ['r' 30 50 45 1]
 ['t' 40 55 80 1]
 ['y' 30 39 100 0]
 ['Jharkand' 10 12 12 0]
 ['Bangalore' 20 23 23 0]
 ['Ecuador' 60 34 15 1]
 ['canada' 80 4 68 0]
 ['c' 25 56 79 1]
 ['c' 12 45 90 0]
 ['asd' 28 43 15 1]
 ['asd' 26 0 32 0]
 ['ad' 32 37 21 1]
 ['sasd' 45 48 12 1]
 ['asd' 56 15 65 0]
 ['asdas' 67 45 33 1]
 ['das' 78 49 8 1]
 ['das' 89 45 18 1]
 ['ads' 21 12 44 0]
 ['ads' 11 20 59 0]
 ['asd' 1 32 70 0]
 [nan 5 20 45 0]
 [nan 42 43 20 1]
 [nan 32 60 30 1]
 [nan 5 15 5 0]
 [nan 20 30 5 0]
 [nan 30 51 2 1]
 [nan 60 60 10 1]
 [nan 10 10 60 0]
 [nan 0 30 0 0]
 [nan 45 45 15 1]]


In [8]:
X = data[0:, 1:-1]

In [9]:
Y = data[:,-1]

In [10]:
X = X.astype('int')

In [11]:
Y = Y.astype('int')

In [12]:
print(X)

[[ 40  45  20]
 [ 50  30  10]
 [ 10  20  70]
 [ 60  45  70]
 [ 30  48  10]
 [ 50  15  30]
 [  5  35  35]
 [  5  20  70]
 [ 60  32  19]
 [ 30  50  45]
 [ 40  55  80]
 [ 30  39 100]
 [ 10  12  12]
 [ 20  23  23]
 [ 60  34  15]
 [ 80   4  68]
 [ 25  56  79]
 [ 12  45  90]
 [ 28  43  15]
 [ 26   0  32]
 [ 32  37  21]
 [ 45  48  12]
 [ 56  15  65]
 [ 67  45  33]
 [ 78  49   8]
 [ 89  45  18]
 [ 21  12  44]
 [ 11  20  59]
 [  1  32  70]
 [  5  20  45]
 [ 42  43  20]
 [ 32  60  30]
 [  5  15   5]
 [ 20  30   5]
 [ 30  51   2]
 [ 60  60  10]
 [ 10  10  60]
 [  0  30   0]
 [ 45  45  15]]


In [13]:
print(Y)

[1 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0
 0 1]


In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [17]:
train = LogisticRegression()

In [18]:
train.fit(X_train,Y_train)

LogisticRegression()

In [19]:
y_pred = train.predict(X_test)

In [20]:
print(y_pred)

[1 0 0 0 1 1 1 0 0 0 1 0]


In [21]:
print(X_test)

[[ 30  48  10]
 [  1  32  70]
 [  5  20  45]
 [ 20  30   5]
 [ 30  51   2]
 [ 89  45  18]
 [ 40  55  80]
 [ 56  15  65]
 [ 30  39 100]
 [ 11  20  59]
 [ 28  43  15]
 [ 80   4  68]]


In [22]:
from sklearn.metrics import r2_score, mean_squared_error

In [23]:
mse = mean_squared_error(Y_test,y_pred)
# print(mse)
print(f"MSE: {mse: .4f}")

MSE:  0.0000


In [24]:
r2 = r2_score(Y_test, y_pred)

In [25]:
print(r2)
print(f"R2 score: {r2*100: .2f}% ")

1.0
R2 score:  100.00% 


In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy*100: .2f}%")


Accuracy:  100.00%


In [27]:
print(f"confusion_matrix: \n {confusion_matrix(Y_test, y_pred)}")


confusion_matrix: 
 [[7 0]
 [0 5]]


In [28]:
new_data1 = [[90,80,80]]
new_data2 = [[25,20,30]]

prediction1 = train.predict(new_data1)
prediction2 = train.predict(new_data2)

print(prediction1)
print(prediction2)

[1]
[0]
